apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}-mysql
  labels:
    app: {name}
spec:
  selector:
    matchLabels:
      app: {name}
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {name}
        tier: mysql
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {name}-mysql-pass
              key: password
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {name}-mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-{name}-pv-claim