apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "mysql-{name}-pv-claim"
  labels:
    app: "{name}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{mysql_size}"