version: "3.8"  # Specify Docker Compose file version

services:
  db:
    image: postgres:15-alpine  # Use the official PostgreSQL image
    restart: always  # Restart the container automatically
    environment:
      POSTGRES_DB: blogp  # Your database name
      POSTGRES_USER: blogp  # Your database user
      POSTGRES_PASSWORD: mysecretpassword  # Set a strong password!
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data with a named volume
    ports:
      - "5432:5432"  # Expose the PostgreSQL port

volumes:
  postgres-data:  # Define the named volume for data persistence
