
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {name}-pv-claim
  labels:
    app: "{name}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{wp_size}"