# Generated by Django 4.2.16 on 2024-11-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='init',
            field=models.BooleanField(default=False),
        ),
    ]
